# Generated by Django 5.1.4 on 2024-12-22 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Citizen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "citizen_number",
                    models.CharField(editable=False, max_length=10, unique=True),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Female", "Female"), ("Male", "Male")], max_length=10
                    ),
                ),
                ("phone_number", models.CharField(max_length=30)),
                ("address", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="RetireeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "yearly_pension_allowance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "citizen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retiree_profile",
                        to="main.citizen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxpayerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_tax_contribution",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "citizen",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taxpayer_profile",
                        to="main.citizen",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Retiree",
        ),
    ]
